### ISSUE TITLE
F-Droid inclusion?

### ISSUE THREAD

**Issue by TPS** [howeyc/crocgui#1]
@howeyc Would you support an [RFP](https://gitlab.com/fdroid/rfp) @ [F-Droid](https://android.izzysoft.de/articles/named/fdroid-intro-1)?  [IfF](https://en.m.wikipedia.org/wiki/Iff) so, [I'd happily open 1 up](https://gitlab.com/fdroid/rfp/issues/new).

**Comment by howeyc** [comment]
I was planning create it myself and submit a merge request at a later time. I just need to figure out the process as I'm sure the build setup is quite different from the usual apps they have on there.

I would ask you hold off and let me figure out the way to get it building their way.

**Comment by TPS** [comment]
Absolutely! 🙇🏾‍♂️  I was just offering my assistance.  Do keep in mind: it's generally several _months_ between RFP & actual publishing on the repo.

**Comment by fossdd** [comment]
@TPS Usually it's not months. If it's a simple gradle app without prop. dependencies the MR is opened shorty and will soon merged. A go app like that could take time if you only opened a RFP.

But @howeyc already opened a MR which looks good! So the MR is in review and after it's merged, there is only to wait. That can take a week or a day.

**Comment by howeyc** [comment]
It's on F-Droid now.
