### ISSUE TITLE
Android GUI should convert spaces to hyphens in the Receive Code

### ISSUE THREAD

**Issue by Nagidal** [howeyc/crocgui#11]
When typing the Receive Code on the on-screen keyboard on an android system the GUI should convert spaces automatically hyphens. This way one could avoid shifting the keyboard layout to special character input after each word. The current GUI v1.4.1 doesn't support this.

**Comment by howeyc** [comment]
I understand the frustration, but I'm hesitant to just mutate/edit user input like that. How is someone supposed to know that spaces get replaced with hypens?

I probably won't do this, but who knows, maybe.

**Comment by Nagidal** [comment]
I can understand why you would not want to fix it. Maybe I only have an issue with this because on the sending side where I ran an older version of croc in debug mode, and I saw that if after 30 seconds it reports no clients in the room, and that seemed to be a reason why I could not receive anything with my android client. The current version of croc seems to check every second for incoming bytes. So, if the user has plenty of time to enter the Receive Code, this can remain unfixed.

**Comment by howeyc** [comment]
Since it's possible to specify your own receive code when sending on the command line I will also support specifying your own when sending using this too. That way the user can specify whatever they want.

I'm closing this, as #13 is the way I'll handle this.
