### ISSUE TITLE
[Feature] Option to change receiver code pattern

### ISSUE THREAD

**Issue by mizzunet** [howeyc/crocgui#13]
Would be nice to have it for changing its pattern to many simple ones, like currently, it's three random words, aren't they? So an option for making it two words, one word, random numbers with certain number of digits etc
Uhm, this thing https://github.com/schollz/croc#custom-code-phrase

**Comment by howeyc** [comment]
Perhaps it would be best for me to allow the user to specify their own.

**Comment by mizzunet** [comment]
> Perhaps it would be best for me to allow the user to specify their own.

I guess so. Thanks
