### ISSUE TITLE
Weird/scary app icon that doesn't match the apps purpose

### ISSUE THREAD

**Issue by carstenhag** [howeyc/crocgui#15]
Hello there, randomly saw this app on the f-droid starting page. Shortly looked at it, but the app icon distracts me from installing it. It's a really angry crocodile. It could be good on something like a Warez forum, but not on an app to privately share files :P.

**Comment by carstenhag** [comment]
Hi, why did you close it without even responding? :(

**Comment by howeyc** [comment]
I didn't know if serious or joking.

**Comment by carstenhag** [comment]
I am 100% serious. I do realize that sounds silly and sarcastic, but this

![Bildschirmfoto 2021-04-14 um 22 03 27](https://user-images.githubusercontent.com/3776997/114771892-6b2c6600-9d6d-11eb-8b88-d64546c7ab42.png)
looks like ![](https://i0.wp.com/bloody-disgusting.com/wp-content/uploads/2019/07/king-k-rool.png?resize=768%2C432&ssl=1)
which is the archenemy of the Donkey Kong games.

I would understand that you don't care (I also don't care about some user's requests that I am getting) so no problemo if you don't mind, I just found it sad you didn't respond 😄

**Comment by howeyc** [comment]
I have no attachment to the current icon, and have no desire to seek a replacement. However, if one were provided, it's very likely I would accept without much resistance.

**Comment by whalehub** [comment]
@howeyc @carstenhag I whipped up a little something in Photoshop just now, feel free to use it if you like it.

![croc](https://xbb.datahoarder.dev/VUSu3/YOlaZoRa55.png/raw)

**Comment by howeyc** [comment]
This is fantastic, I will use it.

Any chance you would be up for creating a "featureGraphic" that shows up in the header portion of the store listing. It's 1024x500 in size.

No pressure, I'm to receive the logo, much appreciated.
