### ISSUE TITLE
Automatic Dark Mode

### ISSUE THREAD

**Issue by 2br-2b** [howeyc/crocgui#18]
Hi!

It would be really nice if Dark Mode automatically enabled if the user has that on in their preferences. I didn't realize dark mode existed until reading the issue tracker here.

Android documentation on that can be found [here](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme).

**Comment by howeyc** [comment]
yeah, the fyne library actually has some pull requests related to this, so this could be coming soon
