### ISSUE TITLE
Reduce APK size

### ISSUE THREAD

**Issue by NilsIrl** [howeyc/crocgui#22]
The APK on F-droid is 50 MiB, that is really really big.

It would be nice if it was smaller.

**Comment by NilsIrl** [comment]
Looking at it slightly more closely, the binary "libcroc.so" is there for 4 architectures (arm and x86 for both 32 and 64 bit each), if these were separated in separate APKs, each apk would be around 15 MB each.

**Comment by howeyc** [comment]
I agree it would be nice, but after looking at the metadata build file for the one that does it I just don't see how I can do that the way fyne builds work. Plus I'd likely have to do manual pull requests against fdroid to get all the separate build versions, I prefer the automatic builds process.

**Comment by Max-RM** [comment]
> Current v1.10.9 is at 119 MiB on F-Droid. That actually stopped me from installing it at the beginning.
> 
> I then installed it out of interest how big it would be at the end: on the smartphone it has 157 MiB.
> 
> I'm really sorry that I have to deinstall it now again to free up some space.
> 
> Besides that it's a great working app.

You can delete all unneeded architectures using Apktool M.
