### ISSUE TITLE
Make croc available in share menu

### ISSUE THREAD

**Issue by mrsalo** [howeyc/crocgui#25]
It would be nice, to have croc available in the share menu. 
This would allow to share files or text from other applications (e.g. from a file manager or the gallery, or a link from the browser) easily.
![image1](https://user-images.githubusercontent.com/3208694/132805157-957a3aa6-ac93-4bde-a0d2-62dc1b04c65d.png)

**Comment by mrsalo** [comment]
Sorry I have seen this has already been requested in #17

**Comment by abakum** [comment]
Append crocgui to menu browse file, send file, send multiple file, send selected text. Try https://github.com/abakum/crocgui/commit/a9ea70d3aa4e25f944e40c407e9a9e17e55793b9
