### ISSUE TITLE
[Feature Request] Dark and AMOLED black themes

### ISSUE THREAD

**Issue by forkbomb9** [howeyc/crocgui#3]
The title says it all. I rely a lot on dark and black themes on my phone.

Other apps do it like this:

- [dropdown] Theme:
    * Light
    * Dark
    * Follow system
- [checkbox] AMOLED dark theme

Or something along these lines (could be another wording)

Could be in an "Appareance" section in the settings tab

**Comment by howeyc** [comment]
Yeah. That's definitely something I'm planning. I use dark theme as well. I just got to figure out how to hook it up.

**Comment by forkbomb9** [comment]
If you want help with testing or feedback, give me a shout!

**Comment by howeyc** [comment]
F-Droid has updated, you should see new version with theme selection.
