### ISSUE TITLE
Font for CJK

### ISSUE THREAD

**Issue by gnuhead-chieb** [howeyc/crocgui#36]
CJK characters such as Japanese text are not displayed correctly.
They should be replaced with fonts that can display multiple languages, such as Noto Sans.

**Comment by gnuhead-chieb** [comment]
![Screenshot_20221227-150107_Croc](https://user-images.githubusercontent.com/41156994/209619081-2eba4796-8f36-487d-8cce-5ee7e468e1f0.png)

**Comment by howeyc** [comment]
I added a font selection, and manged to find a TTF font file to use.

**Comment by howeyc** [comment]
In latest release.
