### ISSUE TITLE
could not transfer between anroid-10 and pc connected through wlan from dsl-router

### ISSUE THREAD

**Issue by k3b** [howeyc/crocgui#4]
I have just installed croc 

* on a windows7-64, 
* ubuntu 18.04.5/64 and 
* https://f-droid.org/en/packages/com.github.howeyc.crocgui/ (version 1.4.1) on a non-rooted android-10

All three computers are connected via wlan to the same dsl-router (and have a working connection to the internet)

* works as expected: ubuntu -> ubuntu
* works as expected: ubuntu -> windows7
* not tested: windows7 -> ubuntu
* error: android -> ubuntu
  * Error message on ubuntu: securing channel...2021/03/25 13:27:08 room not ready
* error: ubuntu -> android
  * Error message on android: "could not connect to: found no addresses to connect"
* error: windows -> android
  * Error message on android: "could not connect to: found no addresses to connect"
  
  since transfer ubuntu -> windows7 works i assume the problem lies on the android-10 side. Any ideas how to find out what went wrong?

do you know how the tranfer is done via tcp/ip ?

as far as i know android does not tolerate android-ip-server-ports below port 8000

**Comment by howeyc** [comment]
That sounds like password/relay issue (room not ready). Can you set your settings page to look like screenshot in the README, and try again?

**Comment by Nagidal** [comment]
I have a very similar issue. It seems that croc has a timer of 30 seconds for any client to enter the receive code and join the room.

**Comment by k3b** [comment]
I tried with "--relay croc.schollz.com:9009,9010,9011,9012,9013"

* android -> ubuntu via public internet works
* croc --relay croc.schollz.com:9009,9010,9011,9012,9013  send ps.txt
  * ubuntu -> ubuntu works
  * ubuntu -> android does not wok
    * android eror: room not ready.
  * windows -> android does not wok
    * android eror: room not ready.

**Comment by howeyc** [comment]
Could you attach a screenshot of the settings tab in crocgui on android?

**Comment by k3b** [comment]
finally i got it working between android-10 and pc in the same wlan wihtout active internetconnection

* pc (ubuntu) has ip adress 192.168.2.112
* pc terminal window#1 croc relay
* pc terminal window#2 croc -relay 192.168.2.112:9009 send --code test myfile.txt
* android settings relay
  * Adress 192.168.2.112:9009
  * ports 9010,9011,9012,9013
  * Password pass123
