### ISSUE TITLE
Upgrade the croc version

### ISSUE THREAD

**Issue by TJNOV** [howeyc/crocgui#46]
croc is not compatible with older versions after upgrading to version 10.0 
[v9.6.16 was a breaking change so I have re-released it as v10.0.0 to signal that. clients must be >=v9.6.16 or >=v10 to be compatible.
](https://github.com/schollz/croc/releases/tag/v10.0.0)

**Comment by howeyc** [comment]
I updated it. Usually takes a week to show up in fdroid.

**Comment by TJNOV** [comment]
Can a standalone apk file be provided?

**Comment by howeyc** [comment]
I added an APK to the release.
