### ISSUE TITLE
Sending from Android device removes filetype

### ISSUE THREAD

**Issue by ram02z** [howeyc/crocgui#5]
When sending an image/pdf, the file loses its filetype and its name changes to a 4 digit number. Not sure if this is intentional or a workaround of some sort, but its pretty annoying.

**Comment by howeyc** [comment]
I am aware. Has to with how android system passes URI to application on selection. Will be fixed in next version.

**Comment by howeyc** [comment]
Please try latest release when you get a chance, it should be fixed now.
