### ISSUE TITLE
Input field issues on Android 11

### ISSUE THREAD

**Issue by Bandie** [howeyc/crocgui#6]
Hello!

### Hardware
- Pixel 4a

### OS
- Android 11

### Situation
I installed the app successfully and try to make some settings or receive some files.
When using the input fields, like for the host settings or the passphrase, I am able to type into the input field but I'm not able to remove typos or the whole passphrase. Even mark and cut didn't work sadly.

### Wild assumption
Is it possible that fyne is not ready for Android 11 yet? Maybe things can be fixed using another type of input field? idk.

Thanks,

Bandie

**Comment by howeyc** [comment]
Are you using custom keyboard by chance?

I noticed the same when using a custom keyboard myself. I have to use built in Gboard to delete. It's unfortunate and I plan to see what's going on eventually.

**Comment by Bandie** [comment]
I am using the AOSP keyboard. 
I hadn't had time to look if there's an issue about that in fyne yet. 

I hate when libs don't work as expected. :D

**Comment by dmlemos** [comment]
It is happening to me too. Android 10 with AOSP keyboard. No google play services

**Comment by bentolor** [comment]
Same here with LineageOS 17.1 (Android 10) with default ASOP Keyboard in English: "Delete" button has no effect; only workaround is to select all, cut and the start over typing.

Have Play Services installed (GApps Nano i think).

**Comment by howeyc** [comment]
Working with upstream fyne library developers to fix this issue.

**Comment by 2br-2b** [comment]
That's odd - I'm using Android 11 (GrapheneOS) and it's working fine for me with AnySoft Keyboard

**Comment by urlordjames** [comment]
Latest release fixed this for me, thanks @howeyc!
