### ISSUE TITLE
Android GUI should wrap lines in log output

### ISSUE THREAD

**Issue by Nagidal** [howeyc/crocgui#8]
The Croc GUI v1.4.1 on Android does not wrap text then typing out the log lines. You have to enable screen rotation and rotate the screen to see a bit more of the log line, but even then some log outputs are not fully readable.

**Comment by howeyc** [comment]
Yeah, I should improve the ouput/logging.

**Comment by howeyc** [comment]
Latest version v.1.6.0 has this feature.
